apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
    name: ingress-nginx
    namespace: flux-system
spec:
    interval: 2h
    url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: ingress-nginx
    namespace: ingress-nginx
spec:
    releaseName: ingress-nginx
    chart:
        spec:
            chart: ingress-nginx
            version: "4.8.x"
            sourceRef:
                kind: HelmRepository
                name: ingress-nginx
                namespace: flux-system
    interval: 1h
    install:
        remediation:
            retries: 3
    valuesFrom:
        - kind: ConfigMap
          name: ingress-nginx
          valuesKey: ingress-nginx-values
          optional: true
