creation_rules:
    - path_regex: apps/openedx/base/configmaps.yml
      age: "age145kp7g8uere4ds4drqqvrs36tgc639gvdcateu9r45g98zmn752suez9jp"
    - path_regex: .*.enc.yaml
      age: "age145kp7g8uere4ds4drqqvrs36tgc639gvdcateu9r45g98zmn752suez9jp"
