apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/part-of: openedx
  name: cms-job
  namespace: openedx
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - env:
            - name: SERVICE_VARIANT
              value: cms
            - name: DJANGO_SETTINGS_MODULE
              value: cms.envs.tutor.production
          image: docker.io/overhangio/openedx:21.0.0
          name: cms
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
          envFrom:
            - secretRef:
                name: openedx-secrets
      restartPolicy: Never
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/part-of: openedx
  name: lms-job
  namespace: openedx
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - env:
            - name: SERVICE_VARIANT
              value: lms
            - name: DJANGO_SETTINGS_MODULE
              value: lms.envs.tutor.production
          image: docker.io/overhangio/openedx:21.0.0
          name: lms
          volumeMounts:
            - mountPath: /openedx/edx-platform/lms/envs/tutor/
              name: settings-lms
            - mountPath: /openedx/edx-platform/cms/envs/tutor/
              name: settings-cms
            - mountPath: /openedx/config
              name: config
          envFrom:
            - secretRef:
                name: openedx-secrets
      restartPolicy: Never
      volumes:
        - configMap:
            name: openedx-settings-lms
          name: settings-lms
        - configMap:
            name: openedx-settings-cms
          name: settings-cms
        - configMap:
            name: openedx-config
          name: config
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    app.kubernetes.io/version: 21.0.0
  labels:
    app.kubernetes.io/component: job
    app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
    app.kubernetes.io/managed-by: tutor
    app.kubernetes.io/part-of: openedx
  name: mysql-job
  namespace: openedx
spec:
  template:
    metadata:
      annotations:
        app.kubernetes.io/version: 21.0.0
      labels:
        app.kubernetes.io/instance: openedx-O5sXSKK6eS4Ei6StnoV5Bqdp
        app.kubernetes.io/managed-by: tutor
        app.kubernetes.io/part-of: openedx
    spec:
      containers:
        - image: docker.io/mysql:8.4.0
          name: mysql
          envFrom:
            - secretRef:
                name: openedx-secrets
      restartPolicy: Never
