locals {
  module_name = "s3"
  region_mappings = {
    "us-east-1"      = "nvirginia"
    "us-east-2"      = "ohio"
    "us-west-1"      = "ncalifornia"
    "us-west-2"      = "oregon"
    "af-south-1"     = "capetown"
    "ap-east-1"      = "hongkong"
    "ap-southeast-3" = "jakarta"
    "ap-northeast-1" = "tokyo"
    "ap-northeast-2" = "seoul"
    "ap-south-1 "    = "mumbai"
    "ap-northeast-3" = "osaka"
    "ap-southeast-1" = "singapore"
    "ap-southeast-2" = "sydney"
    "ca-central-1"   = "canada"
    "cn-north-1"     = "beijing"
    "cn-northwest-1" = "ningxia"
    "eu-central-1"   = "frankfurt"
    "eu-central-2"   = "zurich"
    "eu-west-1"      = "ireland"
    "eu-west-2"      = "london"
    "eu-south-1"     = "milan"
    "eu-west-3"      = "paris"
    "eu-north-1"     = "stockholm"
    "me-south-1"     = "bahrain"
    "sa-east-1"      = "saopaulo"
  }
}
