apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
    name: eks-auxiliaries
    namespace: flux-system
spec:
    interval: 1h
    path: ./apps/auxiliaries/overlays/dev
    prune: true
    sourceRef:
        kind: GitRepository
        name: flux-system
