apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt-prod
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: uzairqamar1998@gmail.com
        privateKeySecretRef:
            name: letsencrypt-prod
        solvers:
            - http01:
                  ingress:
                      ingressClassName: ingress-nginx # <--- CHANGED from 'class'
                      podTemplate:
                          spec:
                              nodeSelector:
                                  kubernetes.io/os: linux
                      ingressTemplate:
                          metadata:
                              annotations:
                                  nginx.ingress.kubernetes.io/ssl-redirect: "false"
                                  nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
