# This patch uses name-matching to ensure images are preserved
# and only specific containers are updated.
apiVersion: apps/v1
kind: Deployment
metadata:
    name: all-deployments # Placeholder name
spec:
    template:
        spec:
            containers:
                - name: lms
                  envFrom:
                      - secretRef:
                            name: openedx-settings
                - name: cms
                  envFrom:
                      - secretRef:
                            name: openedx-settings
            volumes:
                - name: config
                  configMap: null # Removes the old source
                  secret:
                      secretName: openedx-settings
                      items:
                          - key: lms.env.json
                            path: lms.env.json
                          - key: cms.env.json
                            path: cms.env.json
