# This patch specifically targets the volume and env injection without touching images
apiVersion: apps/v1
kind: Deployment
metadata:
    name: lms # This name is a placeholder; Kustomize matches by target in kustomization.yaml
spec:
    template:
        spec:
            containers:
                - name: lms
                  envFrom:
                      - secretRef:
                            name: openedx-settings
                - name: cms
                  envFrom:
                      - secretRef:
                            name: openedx-settings
            volumes:
                - name: config
                  # We use an empty map to clear the previous configMap reference
                  configMap: null
                  secret:
                      secretName: openedx-settings
                      items:
                          - key: lms.env.json
                            path: lms.env.json
                          - key: cms.env.json
                            path: cms.env.json
